/*
	Copyright 2023 Efabless Corp.

	Author: Mohamed Shalan (mshalan@efabless.com)

	This file is auto-generated by wrapper_gen.py on 2023-11-07

	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at

	    http://www.apache.org/licenses/LICENSE-2.0

	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.

*/


#ifndef IO_TYPES
#define IO_TYPES
#define   __R     volatile const unsigned int
#define   __W     volatile       unsigned int
#define   __RW    volatile       unsigned int
#endif

#define EF_PIN_MUX_FN_SEL1_REG_FN_SEL		0
#define EF_PIN_MUX_FN_SEL1_REG_FN_SEL_LEN	10

typedef struct {
	__RW	fn_sel0;
	__RW	fn_sel1;
	__R 	reserved[958];
	__W 	icr;
	__R 	ris;
	__RW	im;
	__R 	mis;
} EF_PIN_MUX_TYPE;
